[build]
base = "./"
command = "yarn gatsby:build"
publish = "public"

[build.environment]
NETLIFY_USE_YARN = "true"
NODE_VERSION = "16.15.0"
YARN_FLAGS = "--no-ignore-optional --ignore-engines"

[[plugins]]
package = "@netlify/plugin-gatsby"

[dev]
autoLaunch = false
command = "yarn gatsby:start"
framework = "gatsby"
publish = "public"
port = 3000
