// Credentials
export const BIGCOMMERCE_API_ACCESS_TOKEN = process.env.BIGCOMMERCE_API_ACCESS_TOKEN;
export const BIGCOMMERCE_API_CLIENT_ID = process.env.BIGCOMMERCE_API_CLIENT_ID;
export const BIGCOMMERCE_API_SECRET = process.env.BIGCOMMERCE_API_SECRET;
export const BIGCOMMERCE_API_STORE_HASH = process.env.BIGCOMMERCE_API_STORE_HASH;
export const BIGCOMMERCE_API_ACCEPT_HEADER = process.env.BIGCOMMERCE_API_ACCEPT_HEADER;
export const BIGCOMMERCE_API_ACCESS_CONTROL_ALLOW_HEADERS = process.env.BIGCOMMERCE_API_ACCESS_CONTROL_ALLOW_HEADERS;
export const BIGCOMMERCE_API_CORS_ORIGIN = process.env.BIGCOMMERCE_API_CORS_ORIGIN;
export const BIGCOMMERCE_API_ALLOWED_METHODS = process.env.BIGCOMMERCE_API_ALLOWED_METHODS;
export const BIGCOMMERCE_API_SITE_URL = process.env.BIGCOMMERCE_API_SITE_URL;

// Endpoints
export const BIGCOMMERCE_API_HOSTNAME = process.env.GATSBY_BIGCOMMERCE_API_HOSTNAME;
export const BIGCOMMERCE_API_LOGIN_HOSTNAME = process.env.GATSBY_BIGCOMMERCE_API_LOGIN_HOSTNAME;
export const BIGCOMMERCE_API_STORE_URL = `${BIGCOMMERCE_API_HOSTNAME}/stores/${BIGCOMMERCE_API_STORE_HASH}`;

// Request Headers
export const BIGCOMMERCE_API_REQUEST_HEADERS = {
	"Accept": BIGCOMMERCE_API_ACCEPT_HEADER,
	"Content-Type": BIGCOMMERCE_API_ACCEPT_HEADER,
	"X-Auth-Client": BIGCOMMERCE_API_CLIENT_ID,
	"X-Auth-Token": BIGCOMMERCE_API_ACCESS_TOKEN
};

// CORS Headers
export const BIGCOMMERCE_API_CORS_HEADERS = {
	"Access-Control-Allow-Credentials": true,
	"Access-Control-Allow-Headers": BIGCOMMERCE_API_ACCESS_CONTROL_ALLOW_HEADERS,
	"Access-Control-Allow-Methods": BIGCOMMERCE_API_ALLOWED_METHODS,
	"Access-Control-Allow-Origin": BIGCOMMERCE_API_CORS_ORIGIN
};

// Timeouts
export const BIGCOMMERCE_API_TIMEOUT = 30000;
