// Credentials
export const OPTIMIZELY_API_ACCEPT_HEADER = process.env.OPTIMIZELY_API_ACCEPT_HEADER;
export const OPTIMIZELY_API_AUTHORIZATION_HEADER = process.env.OPTIMIZELY_API_AUTHORIZATION_HEADER;
export const OPTIMIZELY_API_ACCEPT_LANGUAGE = process.env.OPTIMIZELY_API_ACCEPT_LANGUAGE;
export const OPTIMIZELY_API_X_EPI_CONTINUATION = process.env.OPTIMIZELY_API_X_EPI_CONTINUATION;
export const OPTIMIZELY_API_USERNAME = process.env.OPTIMIZELY_API_USERNAME;
export const OPTIMIZELY_API_PASSWORD = process.env.OPTIMIZELY_API_PASSWORD;
export const OPTIMIZELY_API_GRANT_TYPE = process.env.OPTIMIZELY_API_GRANT_TYPE;
export const OPTIMIZELY_API_CLIENT_ID = process.env.OPTIMIZELY_API_CLIENT_ID;

// Endpoints
export const OPTIMIZELY_API_HOSTNAME = process.env.GATSBY_OPTIMIZELY_API_HOSTNAME;

// Request Headers
export const OPTIMIZELY_API_REQUEST_HEADERS = {
	"Accept": OPTIMIZELY_API_ACCEPT_HEADER,
	"Content-Type": OPTIMIZELY_API_ACCEPT_HEADER,
	"Authorization": `Bearer ${OPTIMIZELY_API_AUTHORIZATION_HEADER}`
};

// Authentication Body
export const OPTIMIZELY_API_AUTHENTICATION_BODY = {
	username: OPTIMIZELY_API_USERNAME,
	password: OPTIMIZELY_API_PASSWORD,
	grant_type: OPTIMIZELY_API_GRANT_TYPE,
	client_id: OPTIMIZELY_API_CLIENT_ID
};

// Timeouts
export const OPTIMIZELY_API_TIMEOUT = 10000;
